/* Nessuna dipendenza esterna. Tutti i dati dello studente restano nel browser. */
(() => {
'use strict';
const app=document.querySelector('#app'), lessons=window.LESSONS, bank=window.QUESTIONS;
const KEY='gbprof-periodo-v1';
let saved={done:[],last:null}, quiz=null;
try{const old=JSON.parse(localStorage.getItem(KEY));if(old&&Array.isArray(old.done))saved=old;}catch{}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{}};
const byId=id=>lessons.find(l=>l.id===id);
const n=i=>String(i+1).padStart(2,'0');
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;};
const card=(l,i)=>`<a class="card" href="#lezione/${l.id}"><span class="number">LEZIONE ${n(i)} ${saved.done.includes(l.id)?' · RIPASSATA':''}</span><h3>${l.title}</h3><p>${l.subtitle}</p><span class="card-link">Leggi ed esplora gli esempi →</span></a>`;
const buttons=`<div class="actions no-print"><a class="button secondary" href="#stampa">Tutte le lezioni da stampare</a></div>`;
function home(){return `<section class="hero"><div><p class="eyebrow">Grammatica · Seconda superiore · Percorso 03</p><h1>Ogni frase<br>ha i suoi <em>legami.</em></h1><p class="lead">L’analisi del periodo, un passaggio alla volta. Prima comprendiamo le frasi. Poi riconosciamo la struttura.</p><div class="actions"><a class="button" href="#lezione/periodo">Comincia dalle basi →</a><a class="button secondary" href="#lezioni">Esplora le 14 lezioni</a></div></div><div class="hero-graph" aria-label="Vado a casa è la principale; perché sono stanco è una subordinata causale"><p class="graph-label">Leggere un legame</p><div class="hero-node">Vado a casa<small>PRINCIPALE · L’AZIONE</small></div><div class="arrow" aria-hidden="true">↓</div><div class="hero-node child">perché sono stanco<small>SUBORDINATA CAUSALE · IL MOTIVO</small></div><p>Due proposizioni. Un rapporto preciso.<br>La grammatica ci aiuta a vederlo.</p></div></section><div class="wrap"><div class="path-grid"><div class="path-card"><p class="eyebrow">01 · Capire</p><h2>Lezioni ed esempi</h2><p>Spiegazioni distese, confronti e frasi analizzate. Parti dal significato e arriva alla regola.</p><a href="#lezioni">Apri il percorso scritto →</a></div><div class="path-card"><p class="eyebrow">02 · Ricordare</p><h2>Schemi riassuntivi</h2><p>Definizioni, riquadri e frecce, sul modello delle lezioni originali. Una guida per ripassare.</p><a href="#schemi">Apri la raccolta degli schemi →</a></div></div><div class="section-head"><div><p class="eyebrow">Metti alla prova il metodo</p><h2>Dai nomi ai rapporti.</h2><p class="lead">Quattro analisi guidate e una verifica di 14 domande, con spiegazioni e ritorno alle lezioni.</p></div><div class="actions"><a class="button secondary" href="#laboratorio">Analizza insieme a noi</a><a class="button" href="#verifica">Mettiti alla prova</a></div></div><p class="meta">Lezioni segnate come ripassate: ${saved.done.length} su ${lessons.length}. Il progresso è salvato solo su questo dispositivo.</p><div class="progress-track" aria-hidden="true"><span style="width:${saved.done.length/lessons.length*100}%"></span></div>${saved.done.length?'<button class="secondary no-print" data-action="reset-progress">Azzera il progresso di lettura</button>':''}</div>`;}
function index(){return `<div class="wrap"><div class="section-head"><div><p class="eyebrow">01 · Il percorso scritto</p><h1>Capire, prima di classificare.</h1><p class="lead">Leggi le spiegazioni e osserva gli esempi. Gli schemi ti aspettano nella seconda parte del percorso.</p></div></div><label class="search-label" for="lesson-search">Cerca una lezione</label><input class="search" id="lesson-search" type="search" placeholder="Per esempio: causale, principale, gradi…"><p class="meta" id="search-count" role="status">14 lezioni</p><div class="grid" id="lesson-grid">${lessons.map(card).join('')}</div>${buttons}</div>`;}
function sidebar(id){return `<aside class="sidebar no-print" aria-label="Indice delle lezioni"><p class="side-title">01 · Lezioni</p>${lessons.map((l,i)=>`<a href="#lezione/${l.id}" ${id===l.id?'aria-current="page"':''}>${n(i)} · ${l.title}</a>`).join('')}<a href="#schemi">02 · Schemi riassuntivi →</a></aside>`;}
function lesson(id){const l=byId(id);if(!l)return missing();const i=lessons.indexOf(l);return `<div class="wrap lesson-layout">${sidebar(id)}<article class="lesson"><a class="breadcrumb" href="#lezioni">← Tutte le lezioni</a><p class="eyebrow">Lezione ${n(i)} / 14</p><h1>${l.title}</h1><p class="lead">${l.subtitle}</p><div class="lesson-body">${l.body}</div><div class="lesson-end"><button data-action="done" data-id="${l.id}" aria-pressed="${saved.done.includes(id)}">${saved.done.includes(id)?'✓ Lezione segnata come ripassata':'Segna come ripassata'}</button><div class="actions"><a class="button secondary" href="#schema/${l.id}">Ora guarda lo schema →</a><button class="secondary" data-action="print">Stampa questa lezione</button></div><p class="meta">Rielaborazione del materiale di gbprof · Pagine di riferimento: ${l.pages}.</p></div><div class="prev-next">${i?`<a href="#lezione/${lessons[i-1].id}">← ${lessons[i-1].title}</a>`:'<span></span>'}${i<lessons.length-1?`<a href="#lezione/${lessons[i+1].id}">${lessons[i+1].title} →</a>`:'<a href="#schemi">Passa agli schemi →</a>'}</div></article></div>`;}
function map(l){const m=l.map;return `<section class="scheme" aria-labelledby="map-${l.id}"><p class="eyebrow">Schema ${n(lessons.indexOf(l))}</p><h2 id="map-${l.id}">${l.title}</h2><div class="scheme-root">${m.definition}</div>${m.intro?`<p class="scheme-intro">${m.intro}</p>`:''}${m.branches?`<div class="branches">${m.branches.map(b=>`<div class="branch"><h3>${b[0]}</h3><p>${b[1]}</p><p class="sample">${b[2]}</p></div>`).join('')}</div>`:`<div class="chain">${m.chain.map((b,i)=>`${i?'<div class="arrow" aria-hidden="true">↓</div>':''}<div class="chain-node"><b>${b[0]}</b><small>${b[1]}</small></div>`).join('')}</div>`}<p class="scheme-note"><strong>Da ricordare.</strong> ${m.note}</p><div class="scheme-footer"><a href="#lezione/${l.id}">Rileggi spiegazione ed esempi →</a><span>Dal materiale originale, pp. ${l.pages}</span></div></section>`;}
function maps(id){const l=byId(id);if(id&&!l)return missing();return `<div class="wrap"><a class="breadcrumb" href="${id?'#schemi':'#lezioni'}">← ${id?'Tutti gli schemi':'Prima parte: lezioni'}</a><p class="eyebrow">02 · Il ripasso visivo</p><h1>Schemi riassuntivi</h1><p class="lead">Dalla definizione alle forme e agli esempi: segui le frecce e ricostruisci il ragionamento.</p><div class="actions"><button data-action="print">Stampa ${id?'lo schema':'gli schemi'}</button>${id?'<a class="button secondary" href="#schemi">Vedi tutti gli schemi</a>':''}</div>${!id?`<label class="search-label no-print" for="map-search">Cerca uno schema</label><input class="search no-print" id="map-search" type="search" placeholder="Scrivi un argomento…">`:''}<div id="map-list">${(l?[l]:lessons).map(map).join('')}</div></div>`;}
function labs(){return `<div class="wrap quiz-shell"><p class="eyebrow">Laboratorio · Quattro analisi guidate</p><h1>Prova. Poi scopri i passaggi.</h1><p class="lead">Per ogni periodo: cerca i predicati, separa le proposizioni, trova la principale e ricostruisci i legami. Apri un passaggio alla volta dopo averci provato.</p>${window.LABS.map((l,i)=>`<article class="lab-card"><p class="eyebrow">Analisi ${n(i)}</p><h2>${l.title}</h2><p class="lab-sentence">${l.sentence}</p>${l.steps.map((s,j)=>`<details><summary>${j+1}. ${s[0]}</summary><p>${s[1]}</p></details>`).join('')}</article>`).join('')}<aside class="remember"><h2>Usalo per scrivere</h2><p>Trasforma «Piove, ma usciamo» usando una concessiva. Poi scrivi tre periodi su una giornata scolastica: uno con una causa, uno con uno scopo e uno con una condizione. Per ciascuno indica principale, subordinata, forma e grado.</p><details><summary>Una possibile trasformazione</summary><p>«Sebbene piova, usciamo». “Usciamo”: principale. “Sebbene piova”: concessiva esplicita di 1° grado.</p></details></aside><a class="button" href="#verifica">Passa alla verifica →</a></div>`;}
function quizIntro(){if(quiz)return quizPage();return `<div class="wrap quiz-shell"><p class="eyebrow">Verifica · Capire le relazioni</p><h1>Adesso tocca a te.</h1><p class="lead">14 domande: una per lezione, estratta da una banca di 28. Tre risposte possibili, ordine variabile. Dopo ogni scelta trovi la spiegazione; alla fine, un percorso di recupero sugli errori.</p><p>Non c’è un limite di tempo. Il risultato è un aiuto per lo studio, non un voto scolastico.</p>${saved.last?`<p class="notice">Ultima verifica completa su questo dispositivo: <b>${saved.last.score}/${saved.last.total}</b>.</p>`:''}<button data-action="start-quiz">Inizia la verifica →</button><p class="meta">Nessun dato viene inviato. Il risultato resta nel browser; una verifica in corso si interrompe ricaricando la pagina.</p></div>`;}
function startQuiz(ids){const selected=ids?bank.filter(q=>ids.includes(q.lesson)):lessons.map(l=>shuffle(bank.filter(q=>q.lesson===l.id))[0]);quiz={questions:shuffle(selected).map(q=>({...q,options:shuffle(q.answers.map((a,i)=>({text:a,correct:i===0})))})),index:0,answers:[],complete:false,recovery:!!ids};drawQuiz();}
function quizPage(){if(quiz.complete)return report();const q=quiz.questions[quiz.index],a=quiz.answers[quiz.index];return `<div class="wrap quiz-shell"><p class="eyebrow">${quiz.recovery?'Recupero mirato':'Verifica'} · Domanda ${quiz.index+1} / ${quiz.questions.length}</p><div class="progress-track" aria-hidden="true"><span style="width:${quiz.index/quiz.questions.length*100}%"></span></div><h1 class="quiz-question">${q.question}</h1><div class="options" aria-label="Risposte">${q.options.map((o,i)=>`<button class="option ${a?(o.correct?'correct':i===a.choice?'wrong':''):''}" data-action="answer" data-option="${i}" ${a?'disabled':''}>${a?(o.correct?'✓ ':i===a.choice?'✕ ':''):''}${o.text}</button>`).join('')}</div>${a?`<div class="feedback" role="status"><h3>${a.correct?'Risposta corretta':'Rivediamo il ragionamento'}</h3><p>${q.explanation}</p><a href="#lezione/${q.lesson}">Rileggi: ${byId(q.lesson).title}</a></div><div class="actions"><button data-action="next-question">${quiz.index===quiz.questions.length-1?'Mostra il risultato':'Prossima domanda →'}</button></div>`:'<p class="meta">Scegli una risposta: verrà registrata e spiegata subito.</p>'}<p><button class="secondary" data-action="end-quiz">Abbandona questa verifica</button></p></div>`;}
function report(){const score=quiz.answers.filter(a=>a.correct).length,errors=quiz.questions.filter((q,i)=>!quiz.answers[i].correct);return `<div class="wrap quiz-shell"><p class="eyebrow">${quiz.recovery?'Recupero completato':'Verifica completata'}</p><h1>Il tuo punto di partenza.</h1><p class="score">${score}<span class="lead"> / ${quiz.questions.length}</span></p><p>${errors.length?'Rivedi i rapporti che ti hanno messo in difficoltà. Ogni errore ti riporta alla lezione giusta.':'Hai riconosciuto tutti i rapporti proposti. Prova ora a costruire e analizzare periodi tuoi.'}</p>${errors.map(q=>`<article class="report-item"><h3>${byId(q.lesson).title}</h3><p><b>${q.question}</b></p><p>${q.explanation}</p><a href="#lezione/${q.lesson}">Ripassa la lezione →</a></article>`).join('')}<div class="actions">${errors.length?'<button data-action="recovery">Esercita gli argomenti da recuperare</button>':''}<button class="secondary" data-action="start-quiz">Nuova verifica completa</button><button class="secondary" data-action="download-report">Scarica il resoconto</button></div><a href="#laboratorio">Torna alle analisi guidate →</a></div>`;}
function printAll(){return `<div class="wrap"><div class="no-print"><p class="eyebrow">Lettura continua · Stampa</p><h1>Le 14 lezioni, in ordine.</h1><p>Stampa questa pagina o scegli “Salva come PDF” nella finestra di stampa del tuo dispositivo.</p><div class="actions"><button data-action="print">Stampa tutte le lezioni</button><a class="button secondary" href="#schemi">Stampa anche gli schemi →</a></div></div><p class="print-heading">gbprof e Libera · Analisi del periodo · Seconda superiore</p>${lessons.map((l,i)=>`<article class="print-lesson lesson"><p class="eyebrow">Lezione ${n(i)}</p><h1>${l.title}</h1><div class="lesson-body">${l.body}</div></article>`).join('')}</div>`;}
function sources(){return `<div class="wrap quiz-shell"><p class="eyebrow">Fonti e criteri</p><h1>Da dove nasce il percorso.</h1><p>Il materiale di base è <a href="https://drive.google.com/file/d/1YJWTd4o-UTpzbPItgfjZeOOKPMHMVMwS/view" target="_blank" rel="noopener">periodo.pdf di gbprof</a>, 17 pagine. Tutti gli argomenti delle slide sono ripresi. Le spiegazioni distese e i nuovi esempi sono una rielaborazione didattica per la seconda superiore.</p><p>Gli schemi mantengono il modello originale: definizione, ramificazioni, forme ed esempi. Sono ricostruiti come testo e riquadri, per restare leggibili anche su schermi piccoli e nella stampa.</p><h2>Precisazioni introdotte</h2><ul><li>Il conteggio riguarda i predicati, non le singole parole verbali.</li><li>La principale è definita dalla sua indipendenza sintattica; “reggente” non significa necessariamente “principale”.</li><li>Si distinguono asindeto, collegamento con una congiunzione e polisindeto come ripetizione della congiunzione.</li><li>L’incidentale è un inciso; “studioso” non è una relativa implicita.</li><li>Si esplicita il soggetto nelle trasformazioni fra forme esplicite e implicite.</li><li>Nelle temporali il confronto è sempre fra azione della subordinata e azione della reggente.</li><li>I modi verbali più frequenti sono presentati senza trasformarli in regole assolute improprie.</li></ul><h2>Riferimenti per il controllo</h2><ul><li><a href="https://www.treccani.it/enciclopedia/sindeto/" target="_blank" rel="noopener">Treccani · Sindeto</a> e <a href="https://www.treccani.it/enciclopedia/polisindeto/" target="_blank" rel="noopener">Polisindeto</a>.</li><li><a href="https://www.treccani.it/enciclopedia/frasi-relative_%28Enciclopedia-dell%27Italiano%29/" target="_blank" rel="noopener">Treccani · Frasi relative</a>.</li><li><a href="https://www.treccani.it/enciclopedia/frasi-temporali_%28Enciclopedia-dell%27Italiano%29/" target="_blank" rel="noopener">Treccani · Frasi temporali</a>.</li><li><a href="https://dico.unime.it/ufaq/prima-che-tu-costruisca-la-temporale/" target="_blank" rel="noopener">Università di Messina, DICO · “Prima che” tu costruisca la temporale</a>.</li></ul><h2>Uso sul dispositivo</h2><p>Dopo il messaggio “Percorso pronto anche offline”, lezioni, schemi, laboratorio e verifica sono disponibili senza connessione. I collegamenti a Drive, alle fonti e all’indice esterno richiedono internet.</p><p>Su iPad: apri in Safari, usa Condividi e scegli “Aggiungi alla schermata Home”. Negli altri browser usa l’opzione di installazione, se disponibile.</p><p>Le spunte di lettura e l’ultimo punteggio sono conservati solo nel browser. Il sito non invia risposte o dati personali. La verifica in corso resta solo nella memoria della pagina.</p><p class="meta">Revisione didattica: 1 ottobre 2026.</p></div>`;}
function missing(){return '<div class="wrap"><h1>Questa pagina non c’è.</h1><a href="#lezioni">Torna alle lezioni</a></div>';}
function render(){const [route,id]=(location.hash.slice(1)||'home').split('/');const views={home,lezioni:index,lezione:()=>lesson(id),schemi:()=>maps(),schema:()=>maps(id),laboratorio:labs,verifica:quizIntro,stampa:printAll,fonti:sources};app.innerHTML=(views[route]||missing)();document.title=`${route==='lezione'&&byId(id)?byId(id).title+' · ':''}Analisi del periodo · gbprof`;document.querySelectorAll('.top nav a').forEach(a=>{const active=a.hash==='#'+({lezione:'lezioni',schema:'schemi',stampa:'lezioni'}[route]||route);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});window.scrollTo(0,0);document.querySelector('#main').focus({preventScroll:true});}
function drawQuiz(){if(location.hash!=='#verifica'){location.hash='verifica';}else{app.innerHTML=quizPage();window.scrollTo(0,0);document.querySelector('#main').focus({preventScroll:true});}}
app.addEventListener('input',e=>{if(e.target.id==='lesson-search'){const term=e.target.value.toLocaleLowerCase('it');const found=lessons.filter(l=>(l.title+' '+l.subtitle+' '+l.body).toLocaleLowerCase('it').includes(term));document.querySelector('#lesson-grid').innerHTML=found.length?found.map(l=>card(l,lessons.indexOf(l))).join(''):'<p class="empty">Nessuna lezione trovata. Prova un’altra parola.</p>';document.querySelector('#search-count').textContent=`${found.length} lezioni trovate`;}if(e.target.id==='map-search'){const term=e.target.value.toLocaleLowerCase('it');const found=lessons.filter(l=>(l.title+' '+JSON.stringify(l.map)).toLocaleLowerCase('it').includes(term));document.querySelector('#map-list').innerHTML=found.length?found.map(map).join(''):'<p role="status">Nessuno schema trovato.</p>';}});
app.addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const action=b.dataset.action;
 if(action==='print')window.print();
 if(action==='done'){const id=b.dataset.id;saved.done=saved.done.includes(id)?saved.done.filter(x=>x!==id):[...saved.done,id];save();b.textContent=saved.done.includes(id)?'✓ Lezione segnata come ripassata':'Segna come ripassata';b.setAttribute('aria-pressed',saved.done.includes(id));}
 if(action==='reset-progress'){if(confirm('Azzerare le spunte di lettura su questo dispositivo?')){saved.done=[];save();render();}}
 if(action==='start-quiz')startQuiz();
 if(action==='answer'&&quiz&&!quiz.answers[quiz.index]){const choice=Number(b.dataset.option);quiz.answers[quiz.index]={choice,correct:quiz.questions[quiz.index].options[choice].correct};app.innerHTML=quizPage();app.querySelector('[data-action="next-question"]').focus({preventScroll:true});}
 if(action==='next-question'&&quiz&&quiz.answers[quiz.index]){if(quiz.index<quiz.questions.length-1){quiz.index++;}else{quiz.complete=true;if(!quiz.recovery){saved.last={score:quiz.answers.filter(a=>a.correct).length,total:quiz.questions.length};save();}}drawQuiz();}
 if(action==='end-quiz'&&confirm('Abbandonare questa verifica? Le risposte in corso non saranno conservate.')){quiz=null;render();}
 if(action==='recovery'&&quiz){startQuiz([...new Set(quiz.questions.filter((q,i)=>!quiz.answers[i].correct).map(q=>q.lesson))]);}
 if(action==='download-report'&&quiz?.complete){const result=['ANALISI DEL PERIODO · gbprof e Libera',`Risultato: ${quiz.answers.filter(a=>a.correct).length}/${quiz.questions.length}`,'',...quiz.questions.map((q,i)=>`${i+1}. ${q.question}\nRisposta scelta: ${q.options[quiz.answers[i].choice].text}\n${quiz.answers[i].correct?'CORRETTA':'DA RIPASSARE'} · ${q.explanation}\nLezione: ${byId(q.lesson).title}\n`)];const url=URL.createObjectURL(new Blob([result.join('\n')],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='resoconto-analisi-periodo.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
});
window.addEventListener('hashchange',render);render();
const status=document.querySelector('#offline-status');
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(reg=>{const ready=()=>{status.textContent='Percorso pronto anche offline';};if(reg.active)ready();navigator.serviceWorker.ready.then(ready);const showUpdate=()=>{if(reg.waiting&&navigator.serviceWorker.controller)document.querySelector('#update').hidden=false;};showUpdate();reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed')showUpdate();});});document.querySelector('#update-button').onclick=()=>reg.waiting?.postMessage({type:'SKIP_WAITING'});}).catch(()=>{status.textContent='Modalità online · offline non disponibile in questo browser';});let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!refreshing&& !document.querySelector('#update').hidden){refreshing=true;location.reload();}});}else status.textContent='Modalità online';
})();
