/* Lezioni rielaborate da periodo.pdf di gbprof (17 pagine). */
window.LESSONS = [
{
id:'periodo', title:'Dal verbo al periodo', subtitle:'Quante proposizioni ci sono?', pages:'1–2',
body:`<p>Quando parliamo o scriviamo, colleghiamo fatti e pensieri. «Vado a casa perché sono stanco» comunica un’azione e la sua ragione. L’<strong>analisi del periodo</strong> studia come le proposizioni si collegano: quali sono autonome, quali dipendono da altre e quale rapporto esprimono.</p>
<h3>Proposizione e periodo</h3><p>La <strong>proposizione</strong> è una struttura organizzata intorno a un predicato. Il soggetto può essere espresso o sottinteso; nei costrutti impersonali può mancare. Il <strong>periodo</strong> è un’unità sintattica di senso compiuto formata da una o più proposizioni, normalmente delimitata da un punto fermo, interrogativo o esclamativo.</p>
<div class="example"><p>«Marta legge.» → un predicato, una proposizione: <strong>periodo semplice</strong>.</p><p>«Marta legge / e Luca disegna.» → due proposizioni coordinate: <strong>periodo composto</strong>.</p><p>«Marta legge / perché domani ha una verifica.» → una principale e una subordinata: <strong>periodo complesso</strong>.</p></div>
<h3>Conta i predicati, non le parole verbali</h3><p>Un predicato può contenere più forme verbali. «Ho studiato» è un tempo composto; «devo studiare» contiene un verbo servile; «sto studiando» e «comincio a studiare» sono costruzioni fraseologiche. Nell’analisi scolastica le consideriamo ciascuna <strong>un solo predicato</strong>. Anche «sono stanco», predicato nominale, è un’unica unità.</p>
<div class="example"><p>«<b>Devo studiare</b> / perché domani <b>sarò interrogato</b>.» → due proposizioni.</p><p>«<b>Credo</b> / di <b>essere preparato</b>.» → due proposizioni: qui l’infinito introduce una subordinata.</p></div>
<p>Un enunciato può anche essere nominale: «Che bella giornata!». Se un predicato è sottinteso, lo ricostruiamo solo quando il contesto lo permette: «Io leggo un romanzo; Luca, un fumetto» sottintende «legge». Non inventiamo verbi in ogni espressione senza verbo.</p>
<aside class="remember">Metodo: individua i predicati → separa le proposizioni → ricostruisci i legami → assegna i nomi.</aside>`,
map:{definition:'Il periodo collega una o più proposizioni; ogni proposizione ruota intorno a un predicato.', branches:[['Semplice','Una proposizione','Marta legge.'],['Composto','Proposizioni coordinate','Marta legge / e Luca disegna.'],['Complesso','Almeno una subordinata','Marta legge / perché ha una verifica.']], note:'Ho letto · devo leggere · sto leggendo: ciascuna espressione forma un solo predicato.'}
},
{
id:'principale', title:'La proposizione principale', subtitle:'Il punto da cui ricostruire i legami', pages:'3–4',
body:`<p>La <strong>principale</strong> non dipende sintatticamente da un’altra proposizione del periodo. Spesso può stare da sola: «Vado a casa / perché sono stanco». «Vado a casa» è la principale; «perché sono stanco» dipende da essa e ne spiega il motivo.</p><p>La prova del “senso compiuto” aiuta, ma non è una regola assoluta. In «Penso / che tu abbia ragione», «penso» è principale anche se aspettiamo di sapere che cosa penso. Il criterio decisivo è la <strong>mancanza di dipendenza sintattica</strong>.</p>
<h3>La principale non è sempre all’inizio</h3><div class="example"><p>«Quando torno da scuola, / pranzo.»</p><p>La principale è «pranzo». La prima proposizione indica quando avviene l’azione.</p></div>
<h3>Che cosa comunica una frase indipendente?</h3><p>Può informare (<strong>enunciativa o dichiarativa</strong>: «Vado a casa»), porre una domanda (<strong>interrogativa diretta</strong>: «Vai a casa?»), dare un ordine o un invito (<strong>imperativa o esortativa</strong>: «Va’ a casa!»), esprimere un desiderio (<strong>desiderativa</strong>: «Magari fossi a casa!») o un’esclamazione (<strong>esclamativa</strong>: «Quanto sei cresciuto!»). Questi nomi descrivono lo scopo comunicativo.</p>
<h3>L’incidentale: una precisazione inserita</h3><p>«Luca, <em>credo</em>, arriverà domani». «Credo» è un’<strong>incidentale</strong>, inserita come commento. La riconosciamo dalle virgole, parentesi o lineette e dal suo ruolo di inciso. Non va messa sullo stesso piano di “interrogativa” o “esclamativa”: “incidentale” descrive l’inserimento nel discorso, non lo scopo comunicativo.</p>
<aside class="remember">Per trovare la principale chiediti: da quale altra proposizione dipende? Se non dipende da nessuna, hai individuato il centro della struttura.</aside>`,
map:{definition:'La principale non dipende sintatticamente da un’altra proposizione.', branches:[['Informare','Enunciativa / dichiarativa','Vado a casa.'],['Domandare','Interrogativa diretta','Vai a casa?'],['Invitare o ordinare','Esortativa / imperativa','Va’ a casa!'],['Desiderare','Desiderativa','Magari fossi a casa!'],['Esclamare','Esclamativa','Quanto sei cresciuto!']], note:'Incidentale: Luca, credo, arriverà. È un inciso; non è una categoria comunicativa parallela alle altre.'}
},
{
id:'coordinate', title:'La coordinazione', subtitle:'Collegare proposizioni sullo stesso piano', pages:'5',
body:`<p>Due proposizioni sono <strong>coordinate</strong> quando sono collegate sullo stesso piano sintattico: una non dipende dall’altra. In «Vado a casa / e studio», la seconda è coordinata alla principale. La congiunzione suggerisce il rapporto fra le due azioni.</p>
<h3>Tre modi di collegare</h3><div class="example"><p>«Entro, / saluto, / mi siedo.» → <strong>asindeto</strong>: collegamento senza congiunzioni, attraverso la punteggiatura.</p><p>«Entro / e saluto.» → collegamento con una congiunzione (<strong>sindeto</strong>).</p><p>«E entro / e saluto / e mi siedo.» → <strong>polisindeto</strong>: ripetizione della congiunzione.</p></div>
<h3>I rapporti più frequenti</h3><ul><li><strong>Copulativa</strong>: aggiunge. «Leggo <b>e</b> sottolineo».</li><li><strong>Avversativa</strong>: contrappone. «Vorrei uscire, <b>ma</b> devo studiare».</li><li><strong>Disgiuntiva</strong>: propone alternative. «Vieni <b>o</b> resti?».</li><li><strong>Conclusiva</strong>: esprime una conclusione. «È tardi, <b>quindi</b> torno a casa».</li><li><strong>Esplicativa o dichiarativa</strong>: chiarisce. «È un quadrilatero, <b>cioè</b> ha quattro lati».</li><li><strong>Correlativa</strong>: collega con segnali in coppia. «<b>O</b> vieni <b>o</b> resti».</li></ul>
<h3>Si coordinano anche le subordinate</h3><div class="example"><p>«Penso / che Luca studi / e che Marta lavori.»</p><p>«Che Luca studi» e «che Marta lavori» dipendono entrambe da «penso»: la seconda è <strong>coordinata alla subordinata oggettiva</strong>, con lo stesso grado e la stessa funzione.</p></div>
<aside class="remember">“E” non significa automaticamente “due proposizioni”: in «Luca e Marta studiano» collega due nomi e il predicato è uno solo.</aside>`,
map:{definition:'Le coordinate sono sullo stesso piano: una non dipende dall’altra.', branches:[['Senza congiunzione','Asindeto','Entro, saluto, mi siedo.'],['Con una congiunzione','Sindeto','Entro e saluto.'],['Congiunzione ripetuta','Polisindeto','E entro e saluto e mi siedo.']], note:'Una coordinata può collegarsi alla principale oppure a una subordinata. Specifica sempre a quale proposizione si collega.'}
},
{
id:'dipendenze', title:'Reggente, subordinata e gradi', subtitle:'Chi dipende da chi?', pages:'6–8',
body:`<p>Una proposizione è <strong>subordinata</strong> quando dipende sintatticamente da un’altra, detta <strong>reggente</strong>. “Reggente” indica un rapporto: è la proposizione da cui dipende quella che stiamo esaminando. Una principale può essere reggente; anche una subordinata può reggerne un’altra.</p>
<div class="example"><p>«Vado a casa / perché devo studiare.»</p><p>«Vado a casa» = principale e reggente della causale. «Perché devo studiare» = subordinata di <strong>primo grado</strong>, perché dipende direttamente dalla principale.</p></div>
<h3>I gradi misurano i passaggi di dipendenza</h3><div class="example"><p>«Penso / che Marta sia felice / perché ha superato l’esame.»</p><p>1. «Penso»: principale.</p><p>2. «Che Marta sia felice»: oggettiva di <strong>primo grado</strong>, retta da «penso».</p><p>3. «Perché ha superato l’esame»: causale di <strong>secondo grado</strong>, retta da «che Marta sia felice»; spiega la felicità di Marta.</p></div>
<p>Non assegnare il grado contando l’ordine delle proposizioni. In «Quando arrivo, / ti telefono / perché voglio salutarti», temporale e causale dipendono entrambe da «ti telefono»: sono entrambe di primo grado, anche se occupano posizioni diverse.</p>
<p>Una coordinata a una subordinata conserva il grado della subordinata a cui si collega. In «So / che leggi / e che scrivi», le due oggettive sono sullo stesso livello.</p>
<aside class="remember">Per ogni subordinata scrivi prima la sua reggente. Il grado si ricava dal legame, non dalla posizione sulla pagina.</aside>`,
map:{definition:'La reggente sostiene una subordinata; può essere principale oppure subordinata.', chain:[['Penso','Principale e reggente'],['che Marta sia felice','Oggettiva di 1° grado; reggente della causale'],['perché ha superato l’esame','Causale di 2° grado']], note:'Le frecce indicano la dipendenza. Due subordinate rette direttamente dalla principale sono entrambe di 1° grado.'}
},
{
id:'forme', title:'Esplicite e implicite', subtitle:'Due forme, la stessa relazione', pages:'9–17',
body:`<p>Per descrivere una subordinata dobbiamo indicare sia la sua <strong>funzione</strong> (causale, finale, temporale…), sia la sua <strong>forma</strong>. Queste due informazioni rispondono a domande diverse: quale rapporto esprime? Come è costruito il verbo?</p>
<h3>La forma esplicita</h3><p>Ha un verbo di modo finito: <strong>indicativo, congiuntivo o condizionale</strong>. Persona e numero sono riconoscibili nella forma verbale.</p><div class="example"><p>«Resto / perché <b>sono</b> stanco.» → causale esplicita.</p><p>«Spero / che tu <b>venga</b>.» → oggettiva esplicita.</p><p>«Sapevo / che <b>saresti arrivato</b>.» → oggettiva esplicita; il condizionale esprime il futuro rispetto al passato.</p></div>
<h3>La forma implicita</h3><p>Ha un verbo di modo indefinito: <strong>infinito, participio o gerundio</strong>. Occorre ricostruire dal contesto il soggetto e il rapporto logico.</p><div class="example"><p>«Studio / per <b>imparare</b>.» → finale implicita.</p><p>«<b>Finito</b> il compito, / uscii.» → temporale implicita.</p><p>«Pur <b>essendo</b> stanco, / continuo.» → concessiva implicita.</p></div>
<h3>Trasformare senza cambiare il senso</h3><p>«Dopo che ho studiato, esco» diventa «Dopo aver studiato, esco». Il soggetto è sempre “io”. Molte trasformazioni all’infinito richiedono che il soggetto sia lo stesso: «Spero di partire» significa che partirò io; «spero che tu parta» riguarda invece te.</p><p>Non esiste una regola assoluta secondo cui ogni implicita ha lo stesso soggetto della reggente: «Terminata la lezione, gli studenti uscirono» contiene un participio riferito a “la lezione”.</p>
<aside class="remember">Un aggettivo non è una subordinata implicita: «l’alunno studioso» è un gruppo nominale; «l’alunno che studia» contiene una relativa esplicita.</aside>`,
map:{definition:'La funzione dice quale rapporto c’è; la forma dipende dal modo del verbo.', branches:[['Esplicita','Indicativo · congiuntivo · condizionale','Esco / dopo che ho studiato.'],['Implicita','Infinito · participio · gerundio','Esco / dopo aver studiato.']], note:'Prima di trasformare, controlla soggetto, tempo e significato. Non tutte le trasformazioni sono possibili.'}
},
{
id:'soggettiva', title:'La subordinata soggettiva', subtitle:'Un’intera proposizione fa da soggetto', pages:'9',
body:`<p>La <strong>soggettiva</strong> svolge la funzione di soggetto del predicato della reggente. Confronta «È necessario il tuo aiuto» e «È necessario che tu mi aiuti»: al posto del gruppo nominale “il tuo aiuto” troviamo un’intera proposizione.</p><p>La reggente presenta spesso un verbo o una costruzione impersonale: <strong>bisogna, occorre, sembra, pare, si dice, è necessario, è giusto</strong>. Non cercare un soggetto come “io” o “lui” davanti a questi predicati: in questa costruzione il soggetto è proprio la subordinata.</p>
<h3>Forma esplicita</h3><div class="example"><p>«È necessario / <b>che tutti ascoltino</b>.»</p><p>«Sembra / <b>che Luca sia pronto</b>.»</p></div><p>È introdotta normalmente da <strong>che</strong>. Il modo dipende dalla reggente e dal significato: «È evidente che Luca è pronto» presenta un fatto come certo; «È possibile che Luca sia pronto» presenta una possibilità.</p>
<h3>Forma implicita</h3><div class="example"><p>«È necessario / <b>ascoltare</b>.»</p><p>«Mi sembra / <b>di sognare</b>.»</p></div><p>Usa l’infinito, con o senza <strong>di</strong>. Non tutte le costruzioni si trasformano meccanicamente: da «Sembra che Luca vada a casa» non ricaviamo la soggettiva “Sembra andare a casa”. Per iniziare, usa esempi trasparenti come «È utile leggere».</p>
<aside class="remember">Prova la sostituzione: «È necessario questo». “Questo” occupa il posto della soggettiva. Il pronome “mi” in «mi sembra» significa “a me”: non è soggetto.</aside>`,
map:{definition:'Fa da soggetto al predicato della reggente.', intro:'Reggenti frequenti: bisogna · sembra · si dice · è giusto · è necessario.', branches:[['Forma esplicita','Che + verbo di modo finito','È necessario / che tutti ascoltino.'],['Forma implicita','Infinito, con o senza di','È necessario / ascoltare.']], note:'Domanda di controllo: che cosa è necessario? Ascoltare. Non basta riconoscere la parola “che”.'}
},
{
id:'oggettiva', title:'La subordinata oggettiva', subtitle:'Un’intera proposizione fa da oggetto', pages:'10',
body:`<p>La <strong>oggettiva</strong> svolge la funzione di complemento oggetto di un verbo della reggente. «Conosco la risposta» può diventare «So che hai ragione»: un contenuto viene espresso mediante un’intera proposizione.</p><p>Le reggenti frequenti contengono verbi di pensiero, dichiarazione o percezione: <strong>penso, credo, dico, so, vedo, sento</strong>. In «Io penso che tu abbia ragione», il soggetto di “penso” è “io”; «che tu abbia ragione» esprime ciò che penso.</p>
<h3>Forma esplicita</h3><div class="example"><p>«So / <b>che Luca è arrivato</b>.»</p><p>«Penso / <b>che Luca sia arrivato</b>.»</p></div><p>È introdotta normalmente da <strong>che</strong>. Il modo dipende dal verbo reggente e dal senso: non tutte le oggettive vogliono il congiuntivo. Il condizionale può esprimere il futuro nel passato: «Disse che sarebbe tornato».</p>
<h3>Forma implicita</h3><div class="example"><p>«Penso / <b>di avere ragione</b>.»</p><p>«Spero / <b>di superare la prova</b>.»</p></div><p>Usa spesso <strong>di + infinito</strong>. Negli esempi il soggetto della reggente e quello dell’infinito coincidono. Per indicare un soggetto diverso diciamo «Spero che tu superi la prova».</p>
<h3>Soggettiva o oggettiva?</h3><p>«Si dice / che Luca sia partito» contiene una soggettiva, retta da una costruzione impersonale. «Marta dice / che Luca è partito» contiene un’oggettiva: “Marta” è già il soggetto di “dice”.</p><aside class="remember">La domanda “che cosa?” da sola non basta: controlla se la subordinata occupa il posto del soggetto oppure dell’oggetto.</aside>`,
map:{definition:'Fa da complemento oggetto del verbo della reggente.', intro:'Reggenti frequenti: penso · credo · dico · so · vedo · sento.', branches:[['Forma esplicita','Che + verbo di modo finito','Penso / che Luca studi.'],['Forma implicita','Di + infinito, in costruzioni frequenti','Penso / di studiare.']], note:'Marta dice che…: oggettiva. Si dice che…: soggettiva. Guarda la costruzione della reggente.'}
},
{
id:'relativa', title:'La subordinata relativa', subtitle:'Aggiungere informazioni su un nome', pages:'11',
body:`<p>La <strong>relativa</strong> si riferisce a un elemento, detto <strong>antecedente</strong>, che di solito è un nome o un pronome. In «L’alunno <b>che studia</b> sarà promosso», la relativa si riferisce a “l’alunno” e lo precisa. Si inserisce dentro la principale, che ricostruiamo così: «L’alunno sarà promosso».</p><p>Può essere introdotta da <strong>che, cui, il quale</strong> e dalle sue forme flesse, o da un avverbio relativo come “dove”. Il pronome relativo ha anche una funzione nella subordinata: «Il libro <b>che</b> leggo» → leggo il libro, quindi “che” è oggetto; «Il ragazzo <b>che</b> parla» → il ragazzo parla, quindi “che” è soggetto.</p>
<h3>Esplicita e implicita</h3><div class="example"><p>«Cerco un libro / <b>che parli di Roma</b>.» → esplicita.</p><p>«Ho un libro / <b>da leggere</b>.» → implicita: “che posso o devo leggere”.</p></div><p>“L’alunno studioso” può rendere un significato simile a “l’alunno che studia”, ma <strong>non contiene una relativa implicita</strong>: “studioso” è un aggettivo, non un verbo.</p>
<h3>Propria e impropria</h3><p>La relativa <strong>propria</strong> precisa o spiega l’antecedente. Quella <strong>impropria</strong> aggiunge anche un valore come fine, causa o condizione: «Cerco qualcuno <b>che mi aiuti</b>» può significare “affinché mi aiuti”, quindi avere valore finale. Se scrivo «per aiutarmi», ho trasformato il costrutto in una finale implicita, non in una relativa.</p>
<h3>La virgola cambia l’informazione</h3><p>«Gli studenti <b>che hanno finito</b> possono uscire» seleziona solo quelli che hanno finito: relativa <strong>restrittiva</strong>. «Gli studenti, <b>che hanno finito</b>, possono uscire» aggiunge un’informazione su tutti gli studenti di cui si parla: relativa <strong>esplicativa</strong>.</p>`,
map:{definition:'Si riferisce a un antecedente e lo precisa o lo spiega.', intro:'Collegamenti: che · cui · il quale / la quale / i quali / le quali · dove.', branches:[['Relativa propria','Precisa o spiega un antecedente','L’alunno / che studia / sarà promosso.'],['Relativa impropria','Ha anche valore finale, causale, ecc.','Cerco qualcuno / che mi aiuti.']], note:'Esplicita: un libro che posso leggere. Implicita: un libro da leggere. “Un alunno studioso” non contiene una subordinata.'}
},
{
id:'finale', title:'La subordinata finale', subtitle:'Per quale scopo?', pages:'12',
body:`<p>La <strong>finale</strong> indica lo scopo verso cui è diretta l’azione della reggente. Lo scopo è un risultato voluto, che non è necessariamente già stato raggiunto. In «Studio / per superare la prova», superare la prova è l’obiettivo dello studio.</p>
<h3>Forma esplicita</h3><p>Si costruisce soprattutto con <strong>affinché</strong> o <strong>perché + congiuntivo</strong>.</p><div class="example"><p>«Ti spiego il procedimento / <b>affinché tu lo capisca</b>.»</p><p>«Parlo lentamente / <b>perché tutti comprendano</b>.»</p></div><p>Il congiuntivo è richiesto dal costrutto finale. Il soggetto può essere diverso da quello della reggente: io spiego, tu capisci.</p>
<h3>Forma implicita</h3><p>Usa soprattutto <strong>per + infinito</strong>; con alcuni verbi troviamo anche “a” o “di”.</p><div class="example"><p>«Studio / <b>per imparare</b>.»</p><p>«Vado in biblioteca / <b>a studiare</b>.»</p></div><p>Negli esempi il soggetto delle due proposizioni coincide. Per cominciare usa “per + infinito”: rende lo scopo immediatamente riconoscibile.</p>
<h3>La parola “perché” non basta</h3><p>«Apro la finestra <b>perché entri aria</b>» esprime uno scopo: finale. «Apro la finestra <b>perché ho caldo</b>» dà una ragione: causale. Chiediti se la subordinata indica un obiettivo da raggiungere oppure il motivo che spiega l’azione.</p><aside class="remember">Finale = obiettivo voluto. Non confonderla con la consecutiva, che presenta un effetto.</aside>`,
map:{definition:'Indica lo scopo dell’azione: per quale fine?', branches:[['Forma esplicita','Affinché / perché + congiuntivo','Spiego / affinché tu capisca.'],['Forma implicita','Soprattutto per + infinito','Studio / per imparare.']], note:'“Perché tu capisca” = scopo. “Perché non hai capito” = causa.'}
},
{
id:'causale', title:'La subordinata causale', subtitle:'Per quale motivo?', pages:'13',
body:`<p>La <strong>causale</strong> indica il motivo per cui avviene o non avviene ciò che è espresso nella reggente. In «Vado a casa / perché sono stanco», la stanchezza spiega la decisione di tornare a casa.</p>
<h3>Forma esplicita</h3><p>I collegamenti più comuni sono <strong>perché, poiché, siccome, giacché, dal momento che</strong>. Quando si presenta una causa come un fatto, il modo più frequente è l’indicativo.</p><div class="example"><p>«Resto a casa / <b>perché ho la febbre</b>.»</p><p>«<b>Poiché piove</b>, / prendiamo l’ombrello.»</p></div><p>Non imparare però “sempre indicativo”: in costrutti particolari compare il congiuntivo, per esempio quando una causa viene negata: «Non taccio perché non sappia la risposta, ma per prudenza».</p>
<h3>Forma implicita</h3><p>Può usare il <strong>gerundio</strong>, il <strong>participio</strong> oppure l’<strong>infinito</strong>, spesso preceduto da “per”.</p><div class="example"><p>«<b>Avendo perso l’autobus</b>, / arrivai tardi.»</p><p>«<b>Bloccato dalla neve</b>, / rinunciò al viaggio.»</p><p>«Fu premiato / <b>per aver aiutato un compagno</b>.»</p></div>
<h3>Trasforma per controllare</h3><p>«Avendo perso l’autobus» può diventare «poiché avevo perso l’autobus»: la parafrasi rende chiara la causa. Un gerundio non è causale per natura: in «Camminando, parlavamo» può indicare contemporaneità. È il contesto che determina il rapporto.</p><aside class="remember">La causale spiega il fatto. La finale indica ciò che si vuole ottenere: «Studio perché domani ho una prova» / «Studio per superare la prova».</aside>`,
map:{definition:'Indica la causa o il motivo: per quale ragione?', intro:'Perché · poiché · siccome · giacché · dal momento che.', branches:[['Forma esplicita','Di solito indicativo per una causa presentata come reale','Resto / perché ho la febbre.'],['Forma implicita','Gerundio · participio · per + infinito','Avendo perso l’autobus, / arrivai tardi.']], note:'Verifica il senso trasformando l’implicita con “poiché”. Il gerundio può avere anche altri valori.'}
},
{
id:'consecutiva', title:'La subordinata consecutiva', subtitle:'Con quale conseguenza?', pages:'14',
body:`<p>La <strong>consecutiva</strong> esprime la conseguenza di ciò che viene detto nella reggente. Spesso la reggente contiene un elemento che prepara il risultato: <strong>così, tanto, talmente, tale</strong>. In «Ero così stanco / che mi addormentai», la stanchezza raggiunge un’intensità che produce un effetto.</p>
<h3>Forma esplicita</h3><div class="example"><p>«Il rumore era <b>tanto</b> forte / <b>che non sentivo nulla</b>.»</p><p>«Ha insistito <b>al punto</b> / <b>che abbiamo accettato</b>.»</p></div><p>Quando l’effetto è presentato come reale, il modo più frequente è l’<strong>indicativo</strong>. Non è l’unico modo possibile in tutti i contesti. Nell’analisi separa bene le parti: in «così stanco che…», “così stanco” appartiene alla reggente; “che…” introduce la consecutiva.</p>
<h3>Forma implicita</h3><p>È frequente <strong>da + infinito</strong>, spesso in correlazione con “così”, “tanto” o “abbastanza”.</p><div class="example"><p>«Ero così stanco / <b>da addormentarmi subito</b>.»</p><p>«Parlava troppo piano / <b>per essere sentito</b>.»</p></div><p>Il secondo esempio mostra una conseguenza non realizzata: la voce era troppo bassa perché qualcuno lo sentisse.</p>
<h3>Scopo ed effetto</h3><p>«Alzo la voce <b>per farmi sentire</b>» → finale: è il mio obiettivo. «Alzo la voce <b>tanto che tutti mi sentono</b>» → consecutiva: è l’effetto. «Alzo la voce, <b>quindi tutti mi sentono</b>» presenta invece una coordinata conclusiva: significato vicino, struttura diversa.</p><aside class="remember">Cerca insieme i due elementi: il segnale nella reggente e la conseguenza nella subordinata.</aside>`,
map:{definition:'Indica un effetto o una conseguenza.', intro:'Nella reggente: così · tanto · talmente · tale · al punto.', branches:[['Forma esplicita','Che + indicativo per un effetto presentato come reale','Ero così stanco / che mi addormentai.'],['Forma implicita','Spesso da + infinito','Ero così stanco / da addormentarmi.']], note:'“Così” resta nella reggente. La subordinata comincia con “che” o “da”.'}
},
{
id:'temporale', title:'La subordinata temporale', subtitle:'Mettere in ordine le azioni', pages:'15',
body:`<p>La <strong>temporale</strong> colloca nel tempo l’azione della reggente. Può indicare un fatto contemporaneo, precedente o successivo. Per evitare equivoci, in questo percorso confrontiamo sempre <strong>l’azione della subordinata con quella della reggente</strong>.</p>
<div class="example"><p>«Esco / <b>dopo che ho finito i compiti</b>.» → prima finisco i compiti, poi esco: l’azione della subordinata è <strong>anteriore</strong>.</p><p>«Ascolto musica / <b>mentre disegno</b>.» → le azioni sono <strong>contemporanee</strong>.</p><p>«Esco / <b>prima che faccia buio</b>.» → prima esco, poi fa buio: l’azione della subordinata è <strong>posteriore</strong>.</p></div>
<h3>Forma esplicita</h3><p>Usa collegamenti come <strong>quando, mentre, dopo che, appena, finché, prima che</strong>. Si trova spesso l’indicativo; <strong>prima che richiede il congiuntivo</strong>: «Rientro prima che inizi la pioggia».</p>
<h3>Forma implicita</h3><div class="example"><p>«Esco / <b>dopo aver studiato</b>.» → infinito passato.</p><p>«Studio / <b>prima di uscire</b>.» → infinito presente.</p><p>«<b>Uscendo di casa</b>, / incontrai un amico.» → gerundio.</p><p>«<b>Terminata la lezione</b>, / uscimmo.» → participio.</p></div><p>“Durante” da solo introduce normalmente un nome: «durante la lezione» è un complemento, non una proposizione. «Mentre seguivo la lezione» contiene invece un predicato e forma una temporale.</p>
<aside class="remember">Non decidere dal suono di “prima” o “dopo”. Scrivi le due azioni nell’ordine in cui avvengono, poi assegna il rapporto.</aside>`,
map:{definition:'Colloca un’azione nel tempo. Qui il riferimento è l’azione della subordinata rispetto alla reggente.', branches:[['Subordinata anteriore','Prima finisco, poi esco','Esco / dopo che ho finito.'],['Contemporanea','Disegno e ascolto nello stesso tempo','Ascolto / mentre disegno.'],['Subordinata posteriore','Prima esco, poi fa buio','Esco / prima che faccia buio.']], note:'Esplicita: prima che + congiuntivo. Implicita: prima di uscire · dopo aver studiato · terminata la lezione.'}
},
{
id:'concessiva', title:'La subordinata concessiva', subtitle:'Un ostacolo che non impedisce il fatto', pages:'16',
body:`<p>La <strong>concessiva</strong> presenta un fatto che potrebbe impedire o rendere inatteso ciò che accade nella reggente. Il fatto principale avviene comunque: «Benché sia stanco, / continuo a studiare». Ci aspetteremmo una pausa; invece lo studio continua.</p>
<h3>Forma esplicita</h3><p><strong>Benché, sebbene, nonostante, quantunque</strong> si costruiscono normalmente con il <strong>congiuntivo</strong>. <strong>Anche se</strong>, quando presenta un fatto reale, usa normalmente l’<strong>indicativo</strong>.</p><div class="example"><p>«<b>Sebbene piova</b>, / usciamo.»</p><p>«<b>Anche se piove</b>, / usciamo.»</p></div><p>“Anche se” può introdurre anche una concessione ipotetica: «Anche se piovesse, usciremmo». Il modo cambia con il significato.</p>
<h3>Forma implicita</h3><div class="example"><p>«<b>Pur essendo stanco</b>, / studio.» → pur + gerundio.</p><p>«<b>Benché avvertito del pericolo</b>, / proseguì.» → benché + participio.</p></div><p>«Benché stanco» è invece una costruzione ellittica, senza un verbo espresso: sottintende “benché fosse stanco”. Non prendere l’aggettivo “stanco” per un participio solo perché segue “benché”.</p>
<h3>Stesso contrasto, strutture diverse</h3><p>«Piove, <b>ma usciamo</b>» usa una coordinata avversativa. «<b>Sebbene piova</b>, usciamo» usa una subordinata concessiva. «<b>Nonostante la pioggia</b>, usciamo» contiene un complemento concessivo. Il significato è vicino, ma l’analisi cambia.</p><aside class="remember">La concessiva non dà il motivo dell’azione: indica una circostanza nonostante la quale l’azione avviene.</aside>`,
map:{definition:'Indica un ostacolo o un fatto contrario che non impedisce l’azione.', branches:[['Forma esplicita','Benché / sebbene + congiuntivo; anche se + indicativo per fatti reali','Sebbene sia stanco, / studio.'],['Forma implicita','Pur + gerundio; benché + participio','Pur essendo stanco, / studio.']], note:'Nonostante la pioggia = complemento. Nonostante piova = subordinata esplicita.'}
},
{
id:'condizionale', title:'La condizionale e il periodo ipotetico', subtitle:'A quale condizione?', pages:'17',
body:`<p>La <strong>condizionale</strong> esprime la condizione da cui dipende quanto detto nella reggente: «Se studi, / migliori». La condizionale si chiama anche <strong>protasi</strong>; la proposizione che presenta la conseguenza dell’ipotesi si chiama <strong>apodosi</strong>. Insieme formano il <strong>periodo ipotetico</strong>.</p>
<h3>Tre costruzioni fondamentali</h3><div class="example"><p><b>Realtà:</b> «Se studi, / migliorerai». Se + indicativo; nell’apodosi troviamo qui il futuro indicativo. La condizione è presentata come concreta.</p><p><b>Possibilità:</b> «Se avessi tempo, / leggerei quel libro». Congiuntivo imperfetto + condizionale presente.</p><p><b>Irrealtà nel passato:</b> «Se avessi studiato, / avrei superato la prova». Congiuntivo trapassato + condizionale passato: la condizione non si è realizzata.</p></div><p>Il contesto conta: «Se fossi un pesce, vivrei nell’acqua» usa congiuntivo imperfetto e condizionale presente, ma esprime un’ipotesi irreale nel presente. I nomi delle categorie non si ricavano soltanto dai tempi verbali.</p>
<h3>Forma implicita</h3><p>Una condizione può essere espressa con il <strong>gerundio</strong>: «Studiando con costanza, migliorerai» significa qui «se studierai con costanza». È possibile anche «A saperlo prima, sarei venuto».</p>
<h3>Un errore da evitare</h3><p>Nell’italiano standard, per questa ipotesi scrivi «<b>Se avessi tempo, verrei</b>», non “se avrei tempo, verrei”. Questo non significa che dopo ogni “se” sia vietato il condizionale: «Non so se verrebbe» è un’interrogativa indiretta, non una condizionale.</p><aside class="remember">Per analizzare: individua la condizione, poi la conseguenza. Anche se la frase comincia con “se”, la principale è normalmente l’apodosi.</aside>`,
map:{definition:'Protasi = condizione. Apodosi = conseguenza dell’ipotesi.', branches:[['Realtà','Se + indicativo; apodosi qui all’indicativo','Se studi, / migliorerai.'],['Possibilità','Congiuntivo imperfetto + condizionale presente','Se avessi tempo, / leggerei.'],['Irrealtà nel passato','Congiuntivo trapassato + condizionale passato','Se avessi studiato, / avrei superato la prova.']], note:'Implicita: Studiando con costanza, migliorerai. La distinzione possibilità/irrealtà dipende anche dal contesto.'}
}
];

window.LABS = [
{title:'Un motivo per tornare',sentence:'Vado a casa perché sono stanco.',steps:[['Trova i predicati','“Vado” e “sono stanco”: due predicati, quindi due proposizioni. “Sono stanco” è un predicato nominale.'],['Separa e trova la principale','Vado a casa / perché sono stanco. La principale è “Vado a casa”.'],['Ricostruisci il rapporto','La stanchezza è il motivo del ritorno: “perché sono stanco” è causale, esplicita, di 1° grado; dipende da “Vado a casa”.']]},
{title:'Due livelli di dipendenza',sentence:'Penso che Marta sia felice perché ha superato l’esame.',steps:[['Trova i predicati','Penso / sia felice / ha superato: tre predicati. “Ha superato” è un tempo composto e vale come un solo predicato.'],['Individua la principale','“Penso” non dipende da nessuna proposizione. “Che Marta sia felice” esprime ciò che penso: oggettiva esplicita di 1° grado.'],['Segui il significato','“Perché ha superato l’esame” spiega la felicità di Marta: causale esplicita di 2° grado, retta dall’oggettiva.']]},
{title:'Una relativa dentro la principale',sentence:'Il libro che mi hai prestato è così bello che lo rileggerò.',steps:[['Trova i predicati','Hai prestato / è bello / rileggerò: tre predicati.'],['Ricostruisci la principale interrotta','“Il libro … è così bello” è la principale. “Che mi hai prestato” è una relativa esplicita di 1° grado riferita a “libro”. Il pronome “che” è oggetto di “hai prestato”.'],['Interpreta il secondo “che”','“Che lo rileggerò” è una consecutiva esplicita di 1° grado, retta dalla principale. “Così bello” annuncia l’effetto. I due “che” hanno funzioni diverse.']]},
{title:'Coordinare subordinate',sentence:'Quando avrò finito i compiti e avrò riordinato la stanza, uscirò per incontrare gli amici.',steps:[['Conta senza dividere i tempi composti','Avrò finito / avrò riordinato / uscirò / incontrare: quattro predicati.'],['Trova il centro','“Uscirò” è la principale. “Quando avrò finito i compiti” è temporale esplicita di 1° grado.'],['Collega il resto','“E avrò riordinato la stanza” è coordinata copulativa alla temporale, sempre di 1° grado: “quando” vale anche per essa. “Per incontrare gli amici” è finale implicita di 1° grado, retta da “uscirò”.']]}
];
